-- Step 1: clean baseline for a NEW, EMPTY Supabase project.
-- Paste this entire file into Supabase > SQL Editor > New query, then Run.
-- Do not run on a project that already has application tables in public.
-- Generated from the historical PostgreSQL export; no user or activity rows.
-- New contributors need only this committed file, not the ignored old dump.
-- Maintainers with a trusted local dump can regenerate it with
-- python backend/scripts/build_supabase_sql_editor_bootstrap.py
BEGIN;
SET LOCAL client_encoding = 'UTF8';
SET LOCAL standard_conforming_strings = on;
SET LOCAL lock_timeout = '10s';

-- Baseline tables
CREATE TABLE public."achievements" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "title" varchar(160) NOT NULL,
    "description" text,
    "condition_type" varchar(80) NOT NULL,
    "condition_value" integer NOT NULL DEFAULT 1 CHECK ("condition_value" >= 0),
    "reward_exp" integer NOT NULL DEFAULT 0 CHECK ("reward_exp" >= 0),
    "reward_coin" integer NOT NULL DEFAULT 0 CHECK ("reward_coin" >= 0),
    "badge_image_url" varchar(255),
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."admin_activity_logs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "admin_id" bigint NOT NULL CHECK ("admin_id" >= 0),
    "action" varchar(120) NOT NULL,
    "target_type" varchar(80),
    "target_id" bigint CHECK ("target_id" >= 0),
    "detail" text,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."cache" (
    "key" varchar(255) NOT NULL,
    "value" text NOT NULL,
    "expiration" integer NOT NULL
);
CREATE TABLE public."cache_locks" (
    "key" varchar(255) NOT NULL,
    "owner" varchar(255) NOT NULL,
    "expiration" integer NOT NULL
);
CREATE TABLE public."comments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "post_id" bigint NOT NULL CHECK ("post_id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "parent_id" bigint CHECK ("parent_id" >= 0),
    "comment_text" text NOT NULL,
    "status" text NOT NULL DEFAULT 'visible' CHECK ("status" IN ('visible', 'hidden', 'suspended')),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" timestamp without time zone
);
CREATE TABLE public."comment_likes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "comment_id" bigint NOT NULL CHECK ("comment_id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."contents" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "slug" varchar(160) NOT NULL,
    "title" varchar(191) NOT NULL,
    "body" text,
    "source_code" text,
    "status" text NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft', 'published', 'archived')),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "category" varchar(80),
    "icon" varchar(50) NOT NULL DEFAULT 'eco',
    "eyebrow" varchar(255),
    "eyebrow_th" varchar(255),
    "title_th" varchar(255),
    "summary" text,
    "summary_th" text,
    "body_html" text,
    "body_html_th" text,
    "cover_image_url" text,
    "cover_image_alt" varchar(255),
    "cover_image_alt_th" varchar(255),
    "image_credit" varchar(255),
    "image_credit_url" text,
    "references" jsonb,
    "reading_minutes" smallint NOT NULL DEFAULT 5 CHECK ("reading_minutes" >= 0),
    "sort_order" smallint NOT NULL DEFAULT 0 CHECK ("sort_order" >= 0),
    "version" integer NOT NULL DEFAULT 1 CHECK ("version" >= 0),
    "published_at" timestamp without time zone
);
CREATE TABLE public."daily_logins" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "login_date" date NOT NULL,
    "streak_day" integer NOT NULL DEFAULT 1 CHECK ("streak_day" >= 0),
    "reward_claimed" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE public."friends" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "friend_id" bigint NOT NULL CHECK ("friend_id" >= 0),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."friendships" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "requester_id" bigint NOT NULL CHECK ("requester_id" >= 0),
    "addressee_id" bigint NOT NULL CHECK ("addressee_id" >= 0),
    "status" varchar(24) NOT NULL DEFAULT 'pending',
    "accepted_at" timestamp without time zone,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);
CREATE TABLE public."friend_requests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "sender_id" bigint NOT NULL CHECK ("sender_id" >= 0),
    "receiver_id" bigint NOT NULL CHECK ("receiver_id" >= 0),
    "status" text NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'accepted', 'rejected', 'cancelled')),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "name" varchar(160) NOT NULL,
    "type" text NOT NULL CHECK ("type" IN ('seed', 'water', 'fertilizer', 'pesticide', 'booster', 'cosmetic')),
    "description" text,
    "image_url" varchar(255),
    "effect_type" varchar(80),
    "effect_value" integer NOT NULL DEFAULT 0,
    "rarity" text NOT NULL DEFAULT 'common' CHECK ("rarity" IN ('common', 'rare', 'epic', 'legendary')),
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."item_usages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "item_id" bigint NOT NULL CHECK ("item_id" >= 0),
    "simulator_id" bigint CHECK ("simulator_id" >= 0),
    "quantity" integer NOT NULL DEFAULT 1 CHECK ("quantity" >= 0),
    "effect_result" text,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."leaderboards" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "season_id" bigint NOT NULL CHECK ("season_id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "score" integer NOT NULL DEFAULT 0 CHECK ("score" >= 0),
    "rank_no" integer CHECK ("rank_no" >= 0),
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."migrations" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "migration" varchar(255) NOT NULL,
    "batch" integer NOT NULL
);
CREATE TABLE public."model_assets" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "asset_key" varchar(255) NOT NULL,
    "label" varchar(255),
    "type" varchar(40) NOT NULL DEFAULT 'model',
    "url" varchar(255) NOT NULL,
    "metadata" jsonb,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);
CREATE TABLE public."password_reset_otps" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "otp_hash" varchar(64) NOT NULL,
    "reset_token_hash" varchar(64),
    "attempts" smallint NOT NULL DEFAULT 0 CHECK ("attempts" >= 0),
    "expires_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "verified_at" timestamp without time zone,
    "consumed_at" timestamp without time zone,
    "requested_ip" varchar(45),
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);
CREATE TABLE public."pests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "name_th" varchar(120) NOT NULL,
    "name_en" varchar(120),
    "description" text,
    "image_url" varchar(255),
    "model_url" varchar(255),
    "base_chance" numeric(5,2) NOT NULL DEFAULT 0.00,
    "damage_per_turn" integer NOT NULL DEFAULT 0 CHECK ("damage_per_turn" >= 0),
    "behavior" text,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" timestamp without time zone
);
CREATE TABLE public."pest_condition_rules" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "pest_id" bigint NOT NULL CHECK ("pest_id" >= 0),
    "plant_id" bigint CHECK ("plant_id" >= 0),
    "factor" varchar(80) NOT NULL,
    "operator" text NOT NULL CHECK ("operator" IN ('below', 'above', 'between', 'outside')),
    "min_value" numeric(8,2),
    "max_value" numeric(8,2),
    "chance_delta" numeric(5,2) NOT NULL DEFAULT 0.00,
    "severity" integer NOT NULL DEFAULT 1 CHECK ("severity" >= 0),
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);
CREATE TABLE public."pest_treatments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "pest_id" bigint NOT NULL CHECK ("pest_id" >= 0),
    "name" varchar(160) NOT NULL,
    "description" text,
    "image_url" varchar(255),
    "efficiency" numeric(5,2) NOT NULL DEFAULT 0.00,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."plants" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "name_th" varchar(120) NOT NULL,
    "name_en" varchar(120),
    "description" text,
    "base_image_url" varchar(255),
    "base_model_url" varchar(255),
    "water_min" integer NOT NULL DEFAULT 0 CHECK ("water_min" >= 0),
    "water_max" integer NOT NULL DEFAULT 100 CHECK ("water_max" >= 0),
    "light_min" integer NOT NULL DEFAULT 0 CHECK ("light_min" >= 0),
    "light_max" integer NOT NULL DEFAULT 100 CHECK ("light_max" >= 0),
    "fertilizer_min" integer NOT NULL DEFAULT 0 CHECK ("fertilizer_min" >= 0),
    "fertilizer_max" integer NOT NULL DEFAULT 100 CHECK ("fertilizer_max" >= 0),
    "soil_humidity_min" integer NOT NULL DEFAULT 0 CHECK ("soil_humidity_min" >= 0),
    "soil_humidity_max" integer NOT NULL DEFAULT 100 CHECK ("soil_humidity_max" >= 0),
    "air_humidity_min" integer NOT NULL DEFAULT 0 CHECK ("air_humidity_min" >= 0),
    "air_humidity_max" integer NOT NULL DEFAULT 100 CHECK ("air_humidity_max" >= 0),
    "soil_temp_min" numeric(5,2) NOT NULL DEFAULT 0.00,
    "soil_temp_max" numeric(5,2) NOT NULL DEFAULT 50.00,
    "air_temp_min" numeric(5,2) NOT NULL DEFAULT 0.00,
    "air_temp_max" numeric(5,2) NOT NULL DEFAULT 50.00,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" timestamp without time zone
);
CREATE TABLE public."plant_condition_rules" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "plant_id" bigint NOT NULL CHECK ("plant_id" >= 0),
    "factor" varchar(80) NOT NULL,
    "operator" text NOT NULL CHECK ("operator" IN ('below', 'above', 'between', 'outside')),
    "min_value" numeric(8,2),
    "max_value" numeric(8,2),
    "visual_state" varchar(80) NOT NULL,
    "severity" integer NOT NULL DEFAULT 1 CHECK ("severity" >= 0),
    "health_delta" integer NOT NULL DEFAULT 0,
    "growth_delta" integer NOT NULL DEFAULT 0,
    "analysis_result" text,
    "direction" text,
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);
CREATE TABLE public."plant_growth_stages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "plant_id" bigint NOT NULL CHECK ("plant_id" >= 0),
    "stage_no" integer NOT NULL CHECK ("stage_no" >= 0),
    "stage_name" varchar(100) NOT NULL,
    "required_growth_point" integer NOT NULL DEFAULT 0 CHECK ("required_growth_point" >= 0),
    "image_url" varchar(255),
    "model_url" varchar(255),
    "description" text
);
CREATE TABLE public."plant_histories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "simulator_id" bigint NOT NULL CHECK ("simulator_id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "plant_id" bigint NOT NULL CHECK ("plant_id" >= 0),
    "final_stage_id" bigint CHECK ("final_stage_id" >= 0),
    "final_health" integer NOT NULL DEFAULT 0 CHECK ("final_health" >= 0),
    "total_score" integer NOT NULL DEFAULT 0 CHECK ("total_score" >= 0),
    "duration_days" integer NOT NULL DEFAULT 0 CHECK ("duration_days" >= 0),
    "visibility" text NOT NULL DEFAULT 'private' CHECK ("visibility" IN ('private', 'friends', 'public')),
    "snapshot_image_url" varchar(255),
    "game_state" jsonb,
    "analysis_result" text,
    "direction" text,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" timestamp without time zone
);
CREATE TABLE public."plant_visual_variants" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "plant_id" bigint NOT NULL CHECK ("plant_id" >= 0),
    "stage_id" bigint CHECK ("stage_id" >= 0),
    "state_key" varchar(80) NOT NULL,
    "label" varchar(120),
    "model_url" varchar(255),
    "leaf_color" varchar(24),
    "stem_color" varchar(24),
    "leaf_state" varchar(80),
    "stem_state" varchar(80),
    "scale" numeric(5,2) NOT NULL DEFAULT 1.00,
    "priority" integer NOT NULL DEFAULT 0 CHECK ("priority" >= 0),
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);
CREATE TABLE public."posts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "plant_history_id" bigint CHECK ("plant_history_id" >= 0),
    "simulator_id" bigint CHECK ("simulator_id" >= 0),
    "caption" text,
    "visibility" text NOT NULL DEFAULT 'public' CHECK ("visibility" IN ('private', 'friends', 'public')),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" timestamp without time zone
);
CREATE TABLE public."post_likes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "post_id" bigint NOT NULL CHECK ("post_id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."quests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "title" varchar(160) NOT NULL,
    "description" text,
    "quest_type" text NOT NULL CHECK ("quest_type" IN ('daily', 'weekly', 'story', 'event')),
    "target_type" varchar(80) NOT NULL,
    "target_value" integer NOT NULL DEFAULT 1 CHECK ("target_value" >= 0),
    "reward_exp" integer NOT NULL DEFAULT 0 CHECK ("reward_exp" >= 0),
    "reward_coin" integer NOT NULL DEFAULT 0 CHECK ("reward_coin" >= 0),
    "reward_gem" integer NOT NULL DEFAULT 0 CHECK ("reward_gem" >= 0),
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."seasons" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "name" varchar(160) NOT NULL,
    "description" text,
    "starts_at" timestamp without time zone NOT NULL,
    "ends_at" timestamp without time zone NOT NULL,
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."season_events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "season_id" bigint NOT NULL CHECK ("season_id" >= 0),
    "name" varchar(160) NOT NULL,
    "description" text,
    "event_type" varchar(80) NOT NULL,
    "reward_exp" integer NOT NULL DEFAULT 0 CHECK ("reward_exp" >= 0),
    "reward_coin" integer NOT NULL DEFAULT 0 CHECK ("reward_coin" >= 0),
    "reward_gem" integer NOT NULL DEFAULT 0 CHECK ("reward_gem" >= 0),
    "starts_at" timestamp without time zone NOT NULL,
    "ends_at" timestamp without time zone NOT NULL,
    "is_active" boolean NOT NULL DEFAULT TRUE
);
CREATE TABLE public."sessions" (
    "id" varchar(255) NOT NULL,
    "user_id" bigint CHECK ("user_id" >= 0),
    "ip_address" varchar(45),
    "user_agent" text,
    "payload" text NOT NULL,
    "last_activity" integer NOT NULL
);
CREATE TABLE public."shop_items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "item_id" bigint NOT NULL CHECK ("item_id" >= 0),
    "price_coin" integer NOT NULL DEFAULT 0 CHECK ("price_coin" >= 0),
    "price_gem" integer NOT NULL DEFAULT 0 CHECK ("price_gem" >= 0),
    "stock_limit" integer CHECK ("stock_limit" >= 0),
    "is_active" boolean NOT NULL DEFAULT TRUE,
    "starts_at" timestamp without time zone,
    "ends_at" timestamp without time zone
);
CREATE TABLE public."simulation_logs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "simulator_id" bigint NOT NULL CHECK ("simulator_id" >= 0),
    "day_no" integer NOT NULL CHECK ("day_no" >= 0),
    "growth_point" integer NOT NULL DEFAULT 0 CHECK ("growth_point" >= 0),
    "health" integer NOT NULL DEFAULT 100 CHECK ("health" >= 0),
    "visual_state" varchar(80),
    "visual_variant_id" bigint CHECK ("visual_variant_id" >= 0),
    "visual_overrides" jsonb,
    "water" integer NOT NULL DEFAULT 0 CHECK ("water" >= 0),
    "light" integer NOT NULL DEFAULT 0 CHECK ("light" >= 0),
    "fertilizer" integer NOT NULL DEFAULT 0 CHECK ("fertilizer" >= 0),
    "soil_humidity" integer NOT NULL DEFAULT 0 CHECK ("soil_humidity" >= 0),
    "air_humidity" integer NOT NULL DEFAULT 0 CHECK ("air_humidity" >= 0),
    "soil_temp" numeric(5,2) NOT NULL DEFAULT 0.00,
    "air_temp" numeric(5,2) NOT NULL DEFAULT 0.00,
    "score" integer NOT NULL DEFAULT 0 CHECK ("score" >= 0),
    "analysis_result" text,
    "direction" text,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."simulation_pests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "simulator_id" bigint NOT NULL CHECK ("simulator_id" >= 0),
    "pest_id" bigint NOT NULL CHECK ("pest_id" >= 0),
    "status" text NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'treated', 'expired')),
    "appeared_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "treated_at" timestamp without time zone
);
CREATE TABLE public."simulators" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "plant_id" bigint NOT NULL CHECK ("plant_id" >= 0),
    "mode" text NOT NULL CHECK ("mode" IN ('outdoor', 'greenhouse')),
    "location_name" varchar(191),
    "latitude" numeric(10,7),
    "longitude" numeric(10,7),
    "season" text CHECK ("season" IN ('summer', 'rainy', 'winter')),
    "growth_point" integer NOT NULL DEFAULT 0 CHECK ("growth_point" >= 0),
    "current_stage_id" bigint CHECK ("current_stage_id" >= 0),
    "health" integer NOT NULL DEFAULT 100 CHECK ("health" >= 0),
    "visual_state" varchar(80) NOT NULL DEFAULT 'healthy',
    "visual_variant_id" bigint CHECK ("visual_variant_id" >= 0),
    "visual_overrides" jsonb,
    "water" integer NOT NULL DEFAULT 0 CHECK ("water" >= 0),
    "light" integer NOT NULL DEFAULT 0 CHECK ("light" >= 0),
    "fertilizer" integer NOT NULL DEFAULT 0 CHECK ("fertilizer" >= 0),
    "soil_humidity" integer NOT NULL DEFAULT 0 CHECK ("soil_humidity" >= 0),
    "air_humidity" integer NOT NULL DEFAULT 0 CHECK ("air_humidity" >= 0),
    "soil_temp" numeric(5,2) NOT NULL DEFAULT 0.00,
    "air_temp" numeric(5,2) NOT NULL DEFAULT 0.00,
    "status" text NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'completed', 'failed', 'cancelled')),
    "share_visibility" varchar(16) NOT NULL DEFAULT 'private',
    "state_version" bigint NOT NULL DEFAULT 1 CHECK ("state_version" >= 0),
    "shared_at" timestamp without time zone,
    "live_snapshot_url" varchar(255),
    "started_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ended_at" timestamp without time zone,
    "maturity_reward_claimed_at" timestamp without time zone,
    "maturity_reward_amount" integer NOT NULL DEFAULT 0 CHECK ("maturity_reward_amount" >= 0),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" timestamp without time zone
);
CREATE TABLE public."simulator_comments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "simulator_id" bigint NOT NULL CHECK ("simulator_id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "comment_text" text NOT NULL,
    "status" varchar(24) NOT NULL DEFAULT 'visible',
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "deleted_at" timestamp without time zone
);
CREATE TABLE public."social_notifications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "recipient_id" bigint NOT NULL CHECK ("recipient_id" >= 0),
    "actor_id" bigint NOT NULL CHECK ("actor_id" >= 0),
    "post_id" bigint CHECK ("post_id" >= 0),
    "comment_id" bigint CHECK ("comment_id" >= 0),
    "type" varchar(32) NOT NULL,
    "excerpt" varchar(240),
    "read_at" timestamp without time zone,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);
CREATE TABLE public."users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "username" varchar(80) NOT NULL,
    "email" varchar(191) NOT NULL,
    "email_verified_at" timestamp without time zone,
    "google_id" varchar(255),
    "password" varchar(255) NOT NULL,
    "avatar_url" varchar(255),
    "cover_url" varchar(255),
    "bio" text,
    "role" text NOT NULL DEFAULT 'member' CHECK ("role" IN ('member', 'admin')),
    "level" integer NOT NULL DEFAULT 1 CHECK ("level" >= 0),
    "experience" integer NOT NULL DEFAULT 0 CHECK ("experience" >= 0),
    "coin" integer NOT NULL DEFAULT 0 CHECK ("coin" >= 0),
    "gem" integer NOT NULL DEFAULT 0 CHECK ("gem" >= 0),
    "status" text NOT NULL DEFAULT 'active' CHECK ("status" IN ('suspended', 'active', 'inactive')),
    "last_login_at" timestamp without time zone,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" timestamp without time zone
);
CREATE TABLE public."user_achievements" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "achievement_id" bigint NOT NULL CHECK ("achievement_id" >= 0),
    "unlocked_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."user_items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "item_id" bigint NOT NULL CHECK ("item_id" >= 0),
    "quantity" integer NOT NULL DEFAULT 0 CHECK ("quantity" >= 0),
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."user_quests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "quest_id" bigint NOT NULL CHECK ("quest_id" >= 0),
    "progress" integer NOT NULL DEFAULT 0 CHECK ("progress" >= 0),
    "status" text NOT NULL DEFAULT 'in_progress' CHECK ("status" IN ('in_progress', 'completed', 'claimed')),
    "completed_at" timestamp without time zone,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public."wallet_transactions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK ("id" >= 0),
    "user_id" bigint NOT NULL CHECK ("user_id" >= 0),
    "currency" text NOT NULL CHECK ("currency" IN ('coin', 'gem')),
    "amount" integer NOT NULL,
    "type" text NOT NULL CHECK ("type" IN ('earn', 'spend', 'refund', 'admin_adjust')),
    "reference_type" varchar(80),
    "reference_id" bigint CHECK ("reference_id" >= 0),
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Mark only migrations already represented by these baseline tables.
INSERT INTO public."migrations" ("id", "migration", "batch") VALUES
(1, '2026_06_11_085932_create_sessions_table', 1),
(2, '2026_06_11_120000_add_model_columns', 2),
(3, '2026_06_24_000001_create_plant_visual_variants_table', 3),
(4, '2026_06_24_000002_create_plant_condition_rules_table', 3),
(5, '2026_06_24_000003_create_pest_condition_rules_table', 3),
(6, '2026_06_24_000004_add_visual_state_to_simulations', 3),
(7, '2026_06_25_000001_create_friendships_table', 4),
(8, '2026_06_29_000001_create_model_assets_table', 5),
(9, '2026_06_30_000001_create_simulator_comments_table', 6),
(10, '2026_07_01_000001_add_maturity_reward_to_simulators', 7),
(11, '2026_07_07_000001_add_threading_and_likes_to_comments', 8),
(12, '2026_07_07_100000_add_bio_to_users_table', 9),
(13, '2026_07_07_110000_add_cover_url_to_users_table', 10),
(14, '2026_07_12_000001_add_live_game_state_and_notifications', 11),
(15, '2026_07_12_000002_add_live_snapshot_url_to_simulators', 12),
(16, '2026_07_12_000003_create_password_reset_otps_table', 13),
(17, '2026_07_12_000004_create_cache_table', 14),
(18, '2026_07_13_000001_add_google_id_to_users_table', 15),
(19, '2026_07_13_000002_add_email_verified_at_to_users_table', 16),
(20, '2026_07_14_000001_create_contents_table', 17),
(21, '2026_07_14_000002_create_admin_activity_logs_table', 18),
(22, '2026_07_15_000001_repair_simulator_current_stage_ids', 19);

-- Baseline primary keys and indexes
ALTER TABLE public."achievements" ADD CONSTRAINT "achievements_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_achievements_active" ON public."achievements" ("is_active");
ALTER TABLE public."admin_activity_logs" ADD CONSTRAINT "admin_activity_logs_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_admin_activity_logs_admin_created" ON public."admin_activity_logs" ("admin_id", "created_at");
CREATE INDEX "idx_admin_activity_logs_target" ON public."admin_activity_logs" ("target_type", "target_id");
ALTER TABLE public."cache" ADD CONSTRAINT "cache_pkey" PRIMARY KEY ("key");
ALTER TABLE public."cache_locks" ADD CONSTRAINT "cache_locks_pkey" PRIMARY KEY ("key");
ALTER TABLE public."comments" ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");
CREATE INDEX "fk_comments_user" ON public."comments" ("user_id");
CREATE INDEX "idx_comments_post_created" ON public."comments" ("post_id", "created_at");
CREATE INDEX "idx_comments_status" ON public."comments" ("status");
CREATE INDEX "comments_parent_id_foreign" ON public."comments" ("parent_id");
ALTER TABLE public."comment_likes" ADD CONSTRAINT "comment_likes_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "comment_likes_comment_id_user_id_unique" ON public."comment_likes" ("comment_id", "user_id");
CREATE INDEX "comment_likes_user_id_index" ON public."comment_likes" ("user_id");
ALTER TABLE public."contents" ADD CONSTRAINT "contents_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_contents_slug" ON public."contents" ("slug");
CREATE INDEX "idx_contents_status" ON public."contents" ("status");
CREATE INDEX "contents_category_index" ON public."contents" ("category");
CREATE INDEX "contents_sort_order_index" ON public."contents" ("sort_order");
CREATE INDEX "contents_published_at_index" ON public."contents" ("published_at");
ALTER TABLE public."daily_logins" ADD CONSTRAINT "daily_logins_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_daily_logins_user_date" ON public."daily_logins" ("user_id", "login_date");
ALTER TABLE public."friends" ADD CONSTRAINT "friends_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_friends_pair" ON public."friends" ("user_id", "friend_id");
CREATE INDEX "idx_friends_friend_id" ON public."friends" ("friend_id");
ALTER TABLE public."friendships" ADD CONSTRAINT "friendships_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "friendships_requester_id_addressee_id_unique" ON public."friendships" ("requester_id", "addressee_id");
CREATE INDEX "friendships_addressee_id_status_index" ON public."friendships" ("addressee_id", "status");
ALTER TABLE public."friend_requests" ADD CONSTRAINT "friend_requests_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_friend_request_pair" ON public."friend_requests" ("sender_id", "receiver_id");
CREATE INDEX "idx_friend_requests_receiver_status" ON public."friend_requests" ("receiver_id", "status");
ALTER TABLE public."items" ADD CONSTRAINT "items_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_items_type_active" ON public."items" ("type", "is_active");
ALTER TABLE public."item_usages" ADD CONSTRAINT "item_usages_pkey" PRIMARY KEY ("id");
CREATE INDEX "fk_item_usages_item" ON public."item_usages" ("item_id");
CREATE INDEX "fk_item_usages_simulator" ON public."item_usages" ("simulator_id");
CREATE INDEX "idx_item_usages_user_created" ON public."item_usages" ("user_id", "created_at");
ALTER TABLE public."leaderboards" ADD CONSTRAINT "leaderboards_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_leaderboards_season_user" ON public."leaderboards" ("season_id", "user_id");
CREATE INDEX "fk_leaderboards_user" ON public."leaderboards" ("user_id");
CREATE INDEX "idx_leaderboards_season_score" ON public."leaderboards" ("season_id", "score");
ALTER TABLE public."migrations" ADD CONSTRAINT "migrations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."model_assets" ADD CONSTRAINT "model_assets_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "model_assets_asset_key_unique" ON public."model_assets" ("asset_key");
ALTER TABLE public."password_reset_otps" ADD CONSTRAINT "password_reset_otps_pkey" PRIMARY KEY ("id");
CREATE INDEX "password_reset_otps_user_index" ON public."password_reset_otps" ("user_id", "consumed_at", "created_at");
ALTER TABLE public."pests" ADD CONSTRAINT "pests_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_pests_name_th" ON public."pests" ("name_th");
ALTER TABLE public."pest_condition_rules" ADD CONSTRAINT "pest_condition_rules_pkey" PRIMARY KEY ("id");
CREATE INDEX "pest_condition_rules_pest_id_is_active_index" ON public."pest_condition_rules" ("pest_id", "is_active");
CREATE INDEX "pest_condition_rules_plant_id_factor_index" ON public."pest_condition_rules" ("plant_id", "factor");
ALTER TABLE public."pest_treatments" ADD CONSTRAINT "pest_treatments_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_pest_treatments_pest_id" ON public."pest_treatments" ("pest_id");
ALTER TABLE public."plants" ADD CONSTRAINT "plants_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_plants_name_th" ON public."plants" ("name_th");
CREATE INDEX "idx_plants_name_en" ON public."plants" ("name_en");
ALTER TABLE public."plant_condition_rules" ADD CONSTRAINT "plant_condition_rules_pkey" PRIMARY KEY ("id");
CREATE INDEX "plant_condition_rules_plant_id_factor_is_active_index" ON public."plant_condition_rules" ("plant_id", "factor", "is_active");
CREATE INDEX "plant_condition_rules_visual_state_severity_index" ON public."plant_condition_rules" ("visual_state", "severity");
ALTER TABLE public."plant_growth_stages" ADD CONSTRAINT "plant_growth_stages_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_plant_stage_no" ON public."plant_growth_stages" ("plant_id", "stage_no");
CREATE INDEX "idx_plant_growth_stages_required" ON public."plant_growth_stages" ("plant_id", "required_growth_point");
ALTER TABLE public."plant_histories" ADD CONSTRAINT "plant_histories_pkey" PRIMARY KEY ("id");
CREATE INDEX "fk_plant_histories_simulator" ON public."plant_histories" ("simulator_id");
CREATE INDEX "fk_plant_histories_plant" ON public."plant_histories" ("plant_id");
CREATE INDEX "fk_plant_histories_final_stage" ON public."plant_histories" ("final_stage_id");
CREATE INDEX "idx_plant_histories_user_created" ON public."plant_histories" ("user_id", "created_at");
CREATE INDEX "idx_plant_histories_visibility" ON public."plant_histories" ("visibility");
ALTER TABLE public."plant_visual_variants" ADD CONSTRAINT "plant_visual_variants_pkey" PRIMARY KEY ("id");
CREATE INDEX "plant_visual_variants_plant_id_state_key_index" ON public."plant_visual_variants" ("plant_id", "state_key");
CREATE INDEX "plant_visual_variants_stage_id_state_key_index" ON public."plant_visual_variants" ("stage_id", "state_key");
CREATE INDEX "plant_visual_variants_is_active_priority_index" ON public."plant_visual_variants" ("is_active", "priority");
ALTER TABLE public."posts" ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");
CREATE INDEX "fk_posts_plant_history" ON public."posts" ("plant_history_id");
CREATE INDEX "idx_posts_user_created" ON public."posts" ("user_id", "created_at");
CREATE INDEX "idx_posts_visibility_created" ON public."posts" ("visibility", "created_at");
CREATE INDEX "posts_simulator_id_index" ON public."posts" ("simulator_id");
ALTER TABLE public."post_likes" ADD CONSTRAINT "post_likes_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_post_likes_post_user" ON public."post_likes" ("post_id", "user_id");
CREATE INDEX "idx_post_likes_user" ON public."post_likes" ("user_id");
ALTER TABLE public."quests" ADD CONSTRAINT "quests_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_quests_type_active" ON public."quests" ("quest_type", "is_active");
ALTER TABLE public."seasons" ADD CONSTRAINT "seasons_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_seasons_active_dates" ON public."seasons" ("is_active", "starts_at", "ends_at");
ALTER TABLE public."season_events" ADD CONSTRAINT "season_events_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_season_events_dates" ON public."season_events" ("season_id", "starts_at", "ends_at");
ALTER TABLE public."sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("id");
CREATE INDEX "sessions_user_id_index" ON public."sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" ON public."sessions" ("last_activity");
ALTER TABLE public."shop_items" ADD CONSTRAINT "shop_items_pkey" PRIMARY KEY ("id");
CREATE INDEX "fk_shop_items_item" ON public."shop_items" ("item_id");
CREATE INDEX "idx_shop_items_active_dates" ON public."shop_items" ("is_active", "starts_at", "ends_at");
ALTER TABLE public."simulation_logs" ADD CONSTRAINT "simulation_logs_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_simulation_logs_day" ON public."simulation_logs" ("simulator_id", "day_no");
CREATE INDEX "idx_simulation_logs_created_at" ON public."simulation_logs" ("created_at");
CREATE INDEX "simulation_logs_visual_variant_id_foreign" ON public."simulation_logs" ("visual_variant_id");
ALTER TABLE public."simulation_pests" ADD CONSTRAINT "simulation_pests_pkey" PRIMARY KEY ("id");
CREATE INDEX "fk_simulation_pests_pest" ON public."simulation_pests" ("pest_id");
CREATE INDEX "idx_simulation_pests_simulator_status" ON public."simulation_pests" ("simulator_id", "status");
ALTER TABLE public."simulators" ADD CONSTRAINT "simulators_pkey" PRIMARY KEY ("id");
CREATE INDEX "fk_simulators_current_stage" ON public."simulators" ("current_stage_id");
CREATE INDEX "idx_simulators_user_status" ON public."simulators" ("user_id", "status");
CREATE INDEX "idx_simulators_plant_id" ON public."simulators" ("plant_id");
CREATE INDEX "simulators_visual_variant_id_foreign" ON public."simulators" ("visual_variant_id");
ALTER TABLE public."simulator_comments" ADD CONSTRAINT "simulator_comments_pkey" PRIMARY KEY ("id");
CREATE INDEX "simulator_comments_user_id_foreign" ON public."simulator_comments" ("user_id");
CREATE INDEX "simulator_comments_simulator_id_status_created_at_index" ON public."simulator_comments" ("simulator_id", "status", "created_at");
ALTER TABLE public."social_notifications" ADD CONSTRAINT "social_notifications_pkey" PRIMARY KEY ("id");
CREATE INDEX "social_notifications_recipient_index" ON public."social_notifications" ("recipient_id", "read_at", "created_at");
CREATE INDEX "social_notifications_post_id_type_index" ON public."social_notifications" ("post_id", "type");
ALTER TABLE public."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_users_username" ON public."users" ("username");
CREATE UNIQUE INDEX "uq_users_email" ON public."users" ("email");
CREATE UNIQUE INDEX "users_google_id_unique" ON public."users" ("google_id");
CREATE INDEX "idx_users_status" ON public."users" ("status");
CREATE INDEX "idx_users_role" ON public."users" ("role");
ALTER TABLE public."user_achievements" ADD CONSTRAINT "user_achievements_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_user_achievements_user_achievement" ON public."user_achievements" ("user_id", "achievement_id");
CREATE INDEX "fk_user_achievements_achievement" ON public."user_achievements" ("achievement_id");
ALTER TABLE public."user_items" ADD CONSTRAINT "user_items_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_user_items_user_item" ON public."user_items" ("user_id", "item_id");
CREATE INDEX "fk_user_items_item" ON public."user_items" ("item_id");
ALTER TABLE public."user_quests" ADD CONSTRAINT "user_quests_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX "uq_user_quests_user_quest" ON public."user_quests" ("user_id", "quest_id");
CREATE INDEX "fk_user_quests_quest" ON public."user_quests" ("quest_id");
CREATE INDEX "idx_user_quests_status" ON public."user_quests" ("status");
ALTER TABLE public."wallet_transactions" ADD CONSTRAINT "wallet_transactions_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_wallet_transactions_user_created" ON public."wallet_transactions" ("user_id", "created_at");
CREATE INDEX "idx_wallet_transactions_reference" ON public."wallet_transactions" ("reference_type", "reference_id");
CREATE UNIQUE INDEX "uq_users_email_ci" ON public."users" ((lower("email")));

-- Baseline foreign keys
ALTER TABLE public."admin_activity_logs" ADD CONSTRAINT "fk_admin_activity_logs_admin" FOREIGN KEY ("admin_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."comments" ADD CONSTRAINT "comments_parent_id_foreign" FOREIGN KEY ("parent_id") REFERENCES public."comments" ("id") ON DELETE CASCADE;
ALTER TABLE public."comments" ADD CONSTRAINT "fk_comments_post" FOREIGN KEY ("post_id") REFERENCES public."posts" ("id") ON DELETE CASCADE;
ALTER TABLE public."comments" ADD CONSTRAINT "fk_comments_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."comment_likes" ADD CONSTRAINT "comment_likes_comment_id_foreign" FOREIGN KEY ("comment_id") REFERENCES public."comments" ("id") ON DELETE CASCADE;
ALTER TABLE public."comment_likes" ADD CONSTRAINT "comment_likes_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."daily_logins" ADD CONSTRAINT "fk_daily_logins_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."friends" ADD CONSTRAINT "fk_friends_friend" FOREIGN KEY ("friend_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."friends" ADD CONSTRAINT "fk_friends_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."friendships" ADD CONSTRAINT "friendships_addressee_id_foreign" FOREIGN KEY ("addressee_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."friendships" ADD CONSTRAINT "friendships_requester_id_foreign" FOREIGN KEY ("requester_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."friend_requests" ADD CONSTRAINT "fk_friend_requests_receiver" FOREIGN KEY ("receiver_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."friend_requests" ADD CONSTRAINT "fk_friend_requests_sender" FOREIGN KEY ("sender_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."item_usages" ADD CONSTRAINT "fk_item_usages_item" FOREIGN KEY ("item_id") REFERENCES public."items" ("id");
ALTER TABLE public."item_usages" ADD CONSTRAINT "fk_item_usages_simulator" FOREIGN KEY ("simulator_id") REFERENCES public."simulators" ("id") ON DELETE SET NULL;
ALTER TABLE public."item_usages" ADD CONSTRAINT "fk_item_usages_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."leaderboards" ADD CONSTRAINT "fk_leaderboards_season" FOREIGN KEY ("season_id") REFERENCES public."seasons" ("id") ON DELETE CASCADE;
ALTER TABLE public."leaderboards" ADD CONSTRAINT "fk_leaderboards_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."password_reset_otps" ADD CONSTRAINT "password_reset_otps_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."pest_condition_rules" ADD CONSTRAINT "pest_condition_rules_pest_id_foreign" FOREIGN KEY ("pest_id") REFERENCES public."pests" ("id") ON DELETE CASCADE;
ALTER TABLE public."pest_condition_rules" ADD CONSTRAINT "pest_condition_rules_plant_id_foreign" FOREIGN KEY ("plant_id") REFERENCES public."plants" ("id") ON DELETE CASCADE;
ALTER TABLE public."pest_treatments" ADD CONSTRAINT "fk_pest_treatments_pest" FOREIGN KEY ("pest_id") REFERENCES public."pests" ("id") ON DELETE CASCADE;
ALTER TABLE public."plant_condition_rules" ADD CONSTRAINT "plant_condition_rules_plant_id_foreign" FOREIGN KEY ("plant_id") REFERENCES public."plants" ("id") ON DELETE CASCADE;
ALTER TABLE public."plant_growth_stages" ADD CONSTRAINT "fk_plant_growth_stages_plant" FOREIGN KEY ("plant_id") REFERENCES public."plants" ("id") ON DELETE CASCADE;
ALTER TABLE public."plant_histories" ADD CONSTRAINT "fk_plant_histories_final_stage" FOREIGN KEY ("final_stage_id") REFERENCES public."plant_growth_stages" ("id") ON DELETE SET NULL;
ALTER TABLE public."plant_histories" ADD CONSTRAINT "fk_plant_histories_plant" FOREIGN KEY ("plant_id") REFERENCES public."plants" ("id");
ALTER TABLE public."plant_histories" ADD CONSTRAINT "fk_plant_histories_simulator" FOREIGN KEY ("simulator_id") REFERENCES public."simulators" ("id") ON DELETE CASCADE;
ALTER TABLE public."plant_histories" ADD CONSTRAINT "fk_plant_histories_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."plant_visual_variants" ADD CONSTRAINT "plant_visual_variants_plant_id_foreign" FOREIGN KEY ("plant_id") REFERENCES public."plants" ("id") ON DELETE CASCADE;
ALTER TABLE public."plant_visual_variants" ADD CONSTRAINT "plant_visual_variants_stage_id_foreign" FOREIGN KEY ("stage_id") REFERENCES public."plant_growth_stages" ("id") ON DELETE SET NULL;
ALTER TABLE public."posts" ADD CONSTRAINT "fk_posts_plant_history" FOREIGN KEY ("plant_history_id") REFERENCES public."plant_histories" ("id") ON DELETE SET NULL;
ALTER TABLE public."posts" ADD CONSTRAINT "fk_posts_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."post_likes" ADD CONSTRAINT "fk_post_likes_post" FOREIGN KEY ("post_id") REFERENCES public."posts" ("id") ON DELETE CASCADE;
ALTER TABLE public."post_likes" ADD CONSTRAINT "fk_post_likes_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."season_events" ADD CONSTRAINT "fk_season_events_season" FOREIGN KEY ("season_id") REFERENCES public."seasons" ("id") ON DELETE CASCADE;
ALTER TABLE public."shop_items" ADD CONSTRAINT "fk_shop_items_item" FOREIGN KEY ("item_id") REFERENCES public."items" ("id") ON DELETE CASCADE;
ALTER TABLE public."simulation_logs" ADD CONSTRAINT "fk_simulation_logs_simulator" FOREIGN KEY ("simulator_id") REFERENCES public."simulators" ("id") ON DELETE CASCADE;
ALTER TABLE public."simulation_logs" ADD CONSTRAINT "simulation_logs_visual_variant_id_foreign" FOREIGN KEY ("visual_variant_id") REFERENCES public."plant_visual_variants" ("id") ON DELETE SET NULL;
ALTER TABLE public."simulation_pests" ADD CONSTRAINT "fk_simulation_pests_pest" FOREIGN KEY ("pest_id") REFERENCES public."pests" ("id");
ALTER TABLE public."simulation_pests" ADD CONSTRAINT "fk_simulation_pests_simulator" FOREIGN KEY ("simulator_id") REFERENCES public."simulators" ("id") ON DELETE CASCADE;
ALTER TABLE public."simulators" ADD CONSTRAINT "fk_simulators_current_stage" FOREIGN KEY ("current_stage_id") REFERENCES public."plant_growth_stages" ("id") ON DELETE SET NULL;
ALTER TABLE public."simulators" ADD CONSTRAINT "fk_simulators_plant" FOREIGN KEY ("plant_id") REFERENCES public."plants" ("id");
ALTER TABLE public."simulators" ADD CONSTRAINT "fk_simulators_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."simulators" ADD CONSTRAINT "simulators_visual_variant_id_foreign" FOREIGN KEY ("visual_variant_id") REFERENCES public."plant_visual_variants" ("id") ON DELETE SET NULL;
ALTER TABLE public."simulator_comments" ADD CONSTRAINT "simulator_comments_simulator_id_foreign" FOREIGN KEY ("simulator_id") REFERENCES public."simulators" ("id") ON DELETE CASCADE;
ALTER TABLE public."simulator_comments" ADD CONSTRAINT "simulator_comments_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."user_achievements" ADD CONSTRAINT "fk_user_achievements_achievement" FOREIGN KEY ("achievement_id") REFERENCES public."achievements" ("id") ON DELETE CASCADE;
ALTER TABLE public."user_achievements" ADD CONSTRAINT "fk_user_achievements_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."user_items" ADD CONSTRAINT "fk_user_items_item" FOREIGN KEY ("item_id") REFERENCES public."items" ("id") ON DELETE CASCADE;
ALTER TABLE public."user_items" ADD CONSTRAINT "fk_user_items_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."user_quests" ADD CONSTRAINT "fk_user_quests_quest" FOREIGN KEY ("quest_id") REFERENCES public."quests" ("id") ON DELETE CASCADE;
ALTER TABLE public."user_quests" ADD CONSTRAINT "fk_user_quests_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;
ALTER TABLE public."wallet_transactions" ADD CONSTRAINT "fk_wallet_transactions_user" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON DELETE CASCADE;

-- Keep the migration identity above the imported baseline rows.
SELECT setval(
    pg_get_serial_sequence('public.migrations', 'id'),
    (SELECT MAX(id) FROM public.migrations),
    true
);

COMMIT;
