const messages = {
  en: {
    pageLabel: 'Shop page',
    eyebrow: 'Lab supplies',
    title: 'Shop',
    subtitle: 'Use your coins to prepare the right tools for every growing challenge.',
    itemCount: (count) => `${count} item${count === 1 ? '' : 's'} available`,
    filters: 'Filters',
    showFilters: 'Show filters',
    hideFilters: 'Hide filters',
    activeFilters: (count) => `${count} active`,
    search: 'Search',
    searchItem: 'Search shop items',
    searchPlaceholder: 'Search tools and supplies',
    filterByPrice: 'Filter by price',
    maximumPrice: 'Maximum price',
    upTo: 'Up to',
    categories: 'Categories',
    allCategories: 'All categories',
    latestPurchases: 'Latest purchases',
    noPurchases: 'No purchases yet',
    noPurchasesHint: 'Items you buy will appear here for quick reference.',
    noCategories: 'No categories available',
    resetFilters: 'Reset filters',
    labItem: 'Lab item',
    favoriteSave: (name) => `Save ${name} to favorites`,
    favoriteRemove: (name) => `Remove ${name} from favorites`,
    buy: 'Buy',
    buying: 'Buying…',
    price: 'Price',
    showing: (start, end, total) => `Showing ${start}–${end} of ${total}`,
    noResultsCount: 'No matching items',
    sortLabel: 'Sort shop items',
    sortDefault: 'Recommended',
    sortPriceDesc: 'Price: high to low',
    sortPriceAsc: 'Price: low to high',
    sortNameAsc: 'Name: A–Z',
    sortNameDesc: 'Name: Z–A',
    selected: 'Selected',
    loadingTitle: 'Preparing the shop…',
    loadingDescription: 'We are loading the latest tools and prices.',
    errorTitle: 'The shop could not be loaded',
    errorDescription: 'Check your connection, then try again. Your coins have not been changed.',
    retry: 'Try again',
    emptyTitle: 'The shop is being restocked',
    emptyDescription: 'There are no active items right now. Please check again shortly.',
    noMatchesTitle: 'No items match these filters',
    noMatchesDescription: 'Try another search, category, or a higher maximum price.',
    buyUnavailable: 'This item is not connected to the shop yet.',
    confirmTitle: (name) => `Buy ${name}?`,
    confirmDescription: 'This item will be added to your lab inventory.',
    confirmBuy: 'Buy item',
    cancel: 'Cancel',
    purchaseSuccess: (name) => `${name} was added to your inventory.`,
    purchaseError: 'This item could not be purchased. Please try again.',
    nextPage: 'Next shop page',
    pageNumber: (page) => `Shop page ${page}`,
  },
  th: {
    pageLabel: 'หน้าร้านค้า',
    eyebrow: 'อุปกรณ์ห้องทดลอง',
    title: 'ร้านค้า',
    subtitle: 'ใช้เหรียญเตรียมเครื่องมือที่เหมาะสมสำหรับทุกสถานการณ์ในการปลูก',
    itemCount: (count) => `มีสินค้า ${count} รายการ`,
    filters: 'ตัวกรอง',
    showFilters: 'แสดงตัวกรอง',
    hideFilters: 'ซ่อนตัวกรอง',
    activeFilters: (count) => `ใช้อยู่ ${count} รายการ`,
    search: 'ค้นหา',
    searchItem: 'ค้นหาสินค้าในร้าน',
    searchPlaceholder: 'ค้นหาเครื่องมือและอุปกรณ์',
    filterByPrice: 'กรองตามราคา',
    maximumPrice: 'ราคาสูงสุด',
    upTo: 'ไม่เกิน',
    categories: 'หมวดหมู่',
    allCategories: 'ทุกหมวดหมู่',
    latestPurchases: 'การซื้อล่าสุด',
    noPurchases: 'ยังไม่มีการซื้อ',
    noPurchasesHint: 'สินค้าที่ซื้อจะแสดงที่นี่เพื่อให้เปิดดูได้ง่าย',
    noCategories: 'ยังไม่มีหมวดหมู่',
    resetFilters: 'ล้างตัวกรอง',
    labItem: 'อุปกรณ์ห้องทดลอง',
    favoriteSave: (name) => `บันทึก ${name} เป็นรายการโปรด`,
    favoriteRemove: (name) => `นำ ${name} ออกจากรายการโปรด`,
    buy: 'ซื้อ',
    buying: 'กำลังซื้อ…',
    price: 'ราคา',
    showing: (start, end, total) => `แสดง ${start}–${end} จาก ${total} รายการ`,
    noResultsCount: 'ไม่พบสินค้าที่ตรงกัน',
    sortLabel: 'เรียงสินค้าในร้าน',
    sortDefault: 'สินค้าแนะนำ',
    sortPriceDesc: 'ราคา: สูงไปต่ำ',
    sortPriceAsc: 'ราคา: ต่ำไปสูง',
    sortNameAsc: 'ชื่อ: A–Z',
    sortNameDesc: 'ชื่อ: Z–A',
    selected: 'เลือกอยู่',
    loadingTitle: 'กำลังเตรียมร้านค้า…',
    loadingDescription: 'กำลังโหลดเครื่องมือและราคาล่าสุด',
    errorTitle: 'ไม่สามารถโหลดร้านค้าได้',
    errorDescription: 'ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง เหรียญของคุณยังไม่ถูกหัก',
    retry: 'ลองอีกครั้ง',
    emptyTitle: 'ร้านค้ากำลังเติมสินค้า',
    emptyDescription: 'ขณะนี้ยังไม่มีสินค้าที่เปิดขาย กรุณากลับมาตรวจสอบอีกครั้ง',
    noMatchesTitle: 'ไม่พบสินค้าที่ตรงกับตัวกรอง',
    noMatchesDescription: 'ลองค้นหาคำอื่น เปลี่ยนหมวดหมู่ หรือเพิ่มราคาสูงสุด',
    buyUnavailable: 'สินค้านี้ยังไม่ได้เชื่อมต่อกับร้านค้า',
    confirmTitle: (name) => `ซื้อ ${name} หรือไม่?`,
    confirmDescription: 'สินค้านี้จะถูกเพิ่มไปยังคลังอุปกรณ์ของคุณ',
    confirmBuy: 'ซื้อสินค้า',
    cancel: 'ยกเลิก',
    purchaseSuccess: (name) => `เพิ่ม ${name} ไปยังคลังของคุณแล้ว`,
    purchaseError: 'ไม่สามารถซื้อสินค้านี้ได้ กรุณาลองอีกครั้ง',
    nextPage: 'หน้าร้านค้าถัดไป',
    pageNumber: (page) => `หน้าร้านค้าที่ ${page}`,
  },
}

export function getShopCopy(language) {
  return messages[language === 'th' ? 'th' : 'en']
}
