const messages = {
  en: {
    pageLabel: 'Shop page',
    eyebrow: 'Lab supplies',
    title: 'Shop',
    subtitle: 'Use your coins to prepare the right tools for every growing challenge.',
    itemCount: (count) => `${count} item${count === 1 ? '' : 's'} available`,
    filters: 'Filters',
    showFilters: 'Show filters',
    hideFilters: 'Hide filters',
    activeFilters: (count) => `${count} active`,
    search: 'Search',
    searchItem: 'Search shop items',
    searchPlaceholder: 'Search tools and supplies',
    filterByPrice: 'Filter by price',
    maximumPrice: 'Maximum price',
    upTo: 'Up to',
    categories: 'Categories',
    allCategories: 'All categories',
    latestPurchases: 'Latest purchases',
    noPurchases: 'No purchases yet',
    noPurchasesHint: 'Items you buy will appear here for quick reference.',
    noCategories: 'No categories available',
    resetFilters: 'Reset filters',
    labItem: 'Lab item',
    friendPrank: 'Friend prank',
    favoriteSave: (name) => `Save ${name} to favorites`,
    favoriteRemove: (name) => `Remove ${name} from favorites`,
    buy: 'Buy',
    buying: 'Buying…',
    price: 'Price',
    showing: (start, end, total) => `Showing ${start}–${end} of ${total}`,
    noResultsCount: 'No matching items',
    sortLabel: 'Sort shop items',
    sortDefault: 'Recommended',
    sortPriceDesc: 'Price: high to low',
    sortPriceAsc: 'Price: low to high',
    sortNameAsc: 'Name: A–Z',
    sortNameDesc: 'Name: Z–A',
    selected: 'Selected',
    loadingTitle: 'Preparing the shop…',
    loadingDescription: 'We are loading the latest tools and prices.',
    errorTitle: 'The shop could not be loaded',
    errorDescription: 'Check your connection, then try again. Your coins have not been changed.',
    retry: 'Try again',
    emptyTitle: 'The shop is being restocked',
    emptyDescription: 'There are no active items right now. Please check again shortly.',
    noMatchesTitle: 'No items match these filters',
    noMatchesDescription: 'Try another search, category, or a higher maximum price.',
    buyUnavailable: 'This item is not connected to the shop yet.',
    confirmTitle: (name) => `Buy ${name}?`,
    confirmDescription: 'This item will be added to your lab inventory.',
    quantity: 'Quantity',
    quantityHint: 'Choose from 1 to 99 items.',
    quantityError: 'Enter a whole number from 1 to 99.',
    totalPrice: 'Total price',
    confirmBuy: 'Review order',
    finalConfirmTitle: 'Confirm this purchase?',
    finalConfirmDescription: 'Please review the quantity and total before coins are deducted.',
    finalQuantity: 'Quantity',
    confirmPurchase: 'Confirm purchase',
    cancel: 'Cancel',
    purchaseSuccess: (name, quantity) => `${quantity} × ${name} were added to your inventory.`,
    purchaseError: 'This item could not be purchased. Please try again.',
    notEnoughCurrency: 'You do not have enough coins for this quantity.',
    unavailableError: 'This item is no longer available.',
    nextPage: 'Next shop page',
    pageNumber: (page) => `Shop page ${page}`,
  },
  th: {
    pageLabel: 'หน้าร้านค้า',
    eyebrow: 'อุปกรณ์ห้องทดลอง',
    title: 'ร้านค้า',
    subtitle: 'ใช้เหรียญเตรียมเครื่องมือที่เหมาะสมสำหรับทุกสถานการณ์ในการปลูก',
    itemCount: (count) => `มีสินค้า ${count} รายการ`,
    filters: 'ตัวกรอง',
    showFilters: 'แสดงตัวกรอง',
    hideFilters: 'ซ่อนตัวกรอง',
    activeFilters: (count) => `ใช้อยู่ ${count} รายการ`,
    search: 'ค้นหา',
    searchItem: 'ค้นหาสินค้าในร้าน',
    searchPlaceholder: 'ค้นหาเครื่องมือและอุปกรณ์',
    filterByPrice: 'กรองตามราคา',
    maximumPrice: 'ราคาสูงสุด',
    upTo: 'ไม่เกิน',
    categories: 'หมวดหมู่',
    allCategories: 'ทุกหมวดหมู่',
    latestPurchases: 'การซื้อล่าสุด',
    noPurchases: 'ยังไม่มีการซื้อ',
    noPurchasesHint: 'สินค้าที่ซื้อจะแสดงที่นี่เพื่อให้เปิดดูได้ง่าย',
    noCategories: 'ยังไม่มีหมวดหมู่',
    resetFilters: 'ล้างตัวกรอง',
    labItem: 'อุปกรณ์ห้องทดลอง',
    friendPrank: 'ไอเทมแกล้งเพื่อน',
    favoriteSave: (name) => `บันทึก ${name} เป็นรายการโปรด`,
    favoriteRemove: (name) => `นำ ${name} ออกจากรายการโปรด`,
    buy: 'ซื้อ',
    buying: 'กำลังซื้อ…',
    price: 'ราคา',
    showing: (start, end, total) => `แสดง ${start}–${end} จาก ${total} รายการ`,
    noResultsCount: 'ไม่พบสินค้าที่ตรงกัน',
    sortLabel: 'เรียงสินค้าในร้าน',
    sortDefault: 'สินค้าแนะนำ',
    sortPriceDesc: 'ราคา: สูงไปต่ำ',
    sortPriceAsc: 'ราคา: ต่ำไปสูง',
    sortNameAsc: 'ชื่อ: A–Z',
    sortNameDesc: 'ชื่อ: Z–A',
    selected: 'เลือกอยู่',
    loadingTitle: 'กำลังเตรียมร้านค้า…',
    loadingDescription: 'กำลังโหลดเครื่องมือและราคาล่าสุด',
    errorTitle: 'ไม่สามารถโหลดร้านค้าได้',
    errorDescription: 'ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง เหรียญของคุณยังไม่ถูกหัก',
    retry: 'ลองอีกครั้ง',
    emptyTitle: 'ร้านค้ากำลังเติมสินค้า',
    emptyDescription: 'ขณะนี้ยังไม่มีสินค้าที่เปิดขาย กรุณากลับมาตรวจสอบอีกครั้ง',
    noMatchesTitle: 'ไม่พบสินค้าที่ตรงกับตัวกรอง',
    noMatchesDescription: 'ลองค้นหาคำอื่น เปลี่ยนหมวดหมู่ หรือเพิ่มราคาสูงสุด',
    buyUnavailable: 'สินค้านี้ยังไม่ได้เชื่อมต่อกับร้านค้า',
    confirmTitle: (name) => `ซื้อ ${name} หรือไม่?`,
    confirmDescription: 'สินค้านี้จะถูกเพิ่มไปยังคลังอุปกรณ์ของคุณ',
    quantity: 'จำนวนที่ต้องการซื้อ',
    quantityHint: 'เลือกได้ตั้งแต่ 1 ถึง 99 ชิ้น',
    quantityError: 'กรุณากรอกจำนวนเต็มตั้งแต่ 1 ถึง 99',
    totalPrice: 'ราคารวม',
    confirmBuy: 'ตรวจสอบรายการ',
    finalConfirmTitle: 'ยืนยันการซื้ออีกครั้งหรือไม่?',
    finalConfirmDescription: 'กรุณาตรวจสอบจำนวนและราคารวมก่อนระบบหักเหรียญ',
    finalQuantity: 'จำนวนสินค้า',
    confirmPurchase: 'ยืนยันการซื้อ',
    cancel: 'ยกเลิก',
    purchaseSuccess: (name, quantity) => `เพิ่ม ${name} จำนวน ${quantity} ชิ้นไปยังคลังของคุณแล้ว`,
    purchaseError: 'ไม่สามารถซื้อสินค้านี้ได้ กรุณาลองอีกครั้ง',
    notEnoughCurrency: 'เหรียญของคุณไม่เพียงพอสำหรับจำนวนที่เลือก',
    unavailableError: 'สินค้านี้ไม่พร้อมจำหน่ายแล้ว',
    nextPage: 'หน้าร้านค้าถัดไป',
    pageNumber: (page) => `หน้าร้านค้าที่ ${page}`,
  },
}

export function getShopCopy(language) {
  return messages[language === 'th' ? 'th' : 'en']
}

const thaiShopItems = {
  'Insect Spray': { name: 'สเปรย์กำจัดแมลง', description: 'กำจัดเพลี้ยได้สำเร็จ 100%' },
  'Snail Spray': { name: 'สเปรย์กำจัดหอยทาก', description: 'กำจัดหอยทากได้สำเร็จ 100%' },
  'Fungus Spray': { name: 'สเปรย์กำจัดเชื้อรา', description: 'กำจัดเชื้อราได้สำเร็จ 100%' },
  'Aphid Prank': { name: 'ไอเทมเพลี้ยแกล้งเพื่อน', description: 'ส่งเพลี้ยไปยังพืชที่กำลังปลูก 1 ต้นในสวนของเพื่อน' },
  'Snail Prank': { name: 'ไอเทมหอยทากแกล้งเพื่อน', description: 'ส่งหอยทากไปยังพืชที่กำลังปลูก 1 ต้นในสวนของเพื่อน' },
  'Watering Dose': { name: 'น้ำสำหรับรดพืช', description: 'เติมหลอดน้ำสำรองของพืช น้ำจะค่อย ๆ ลดลงในทุกรอบจำลอง' },
  'Fertilizer Dose': { name: 'ปุ๋ยสำหรับพืช', description: 'เติมหลอดธาตุอาหารของพืช โดยธาตุอาหารจะลดช้ากว่าน้ำ' },
  'Drainage Mix': { name: 'วัสดุช่วยระบายน้ำ', description: 'ลดความชื้นดินส่วนเกินในโหมดกลางแจ้งหลังฝนตกหนัก' },
  'Shade Cloth': { name: 'ผ้าบังแดด', description: 'ลดผลกระทบจากแสงจัดและคลื่นความร้อนชั่วคราว' },
  Windbreak: { name: 'แนวกันลม', description: 'ลดความเครียดจากลมแรงในโหมดกลางแจ้งชั่วคราว' },
  'Frost Cover': { name: 'วัสดุป้องกันอากาศเย็น', description: 'ป้องกันพืชจากอากาศเย็นฉับพลันชั่วคราว' },
}

export function localizeShopItem(item, language) {
  if (language !== 'th') return item
  const localized = thaiShopItems[item?.sourceName ?? item?.name]
  return localized ? { ...item, ...localized } : item
}
