import { useCallback, useEffect, useMemo, useState } from 'react'
import { AppIcon } from '../game/icons/FontAwesomeIcon'
import { getAdminIssueReport, getAdminIssueReports, getIssueAttachment, markAdminIssueReportSeen, updateAdminIssueReportStatus } from '../lib/api'
import './IssueReportsAdmin.css'

const labels = {
  en: { search: 'Search user, email, subject, or reference', allStatus: 'All statuses', allCategory: 'All categories', reference: 'Reference', reporter: 'Reporter', category: 'Category', subject: 'Subject', evidence: 'Evidence', status: 'Status', sent: 'Submitted', view: 'View', empty: 'No reports match these filters.', details: 'Original report', history: 'Permanent update history', publicMessage: 'Public update for the reporter', save: 'Save status update' },
  th: { search: 'ค้นหาผู้ใช้ อีเมล หัวข้อ หรือรหัสรายงาน', allStatus: 'ทุกสถานะ', allCategory: 'ทุกหมวดหมู่', reference: 'รหัสรายงาน', reporter: 'ผู้แจ้ง', category: 'หมวดหมู่', subject: 'หัวข้อ', evidence: 'หลักฐาน', status: 'สถานะ', sent: 'วันที่ส่ง', view: 'เปิดดู', empty: 'ไม่พบรายงานที่ตรงกับตัวกรอง', details: 'รายละเอียดต้นฉบับ', history: 'ประวัติการดำเนินการถาวร', publicMessage: 'ข้อความแจ้งความคืบหน้าถึงผู้ใช้', save: 'บันทึกสถานะ' },
}
const statuses = { new: ['ใหม่', 'New'], under_review: ['กำลังพิจารณา', 'Under review'], in_progress: ['กำลังแก้ไข', 'In progress'], resolved: ['แก้ไขแล้ว', 'Resolved'], closed: ['ปิดเรื่อง', 'Closed'] }
const categories = { simulation: ['ระบบจำลอง', 'Simulation'], interface: ['UI / การแสดงผล', 'Interface'], performance: ['ประสิทธิภาพ', 'Performance'], account: ['บัญชี', 'Account'], content: ['เนื้อหา', 'Content'], other: ['อื่น ๆ', 'Other'] }
const text = (map, key, lang) => map[key]?.[lang === 'th' ? 0 : 1] ?? key
const formatDate = (value, lang) => value ? new Intl.DateTimeFormat(lang === 'th' ? 'th-TH' : 'en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'

function EvidenceImage({ reportId, attachment }) {
  const [src, setSrc] = useState('')
  useEffect(() => { let url = ''; let active = true; getIssueAttachment(reportId, attachment.id).then((blob) => { url = URL.createObjectURL(blob); if (active) setSrc(url) }).catch(() => {}); return () => { active = false; if (url) URL.revokeObjectURL(url) } }, [attachment.id, reportId])
  return src ? <a href={src} target="_blank" rel="noreferrer"><img src={src} alt={attachment.original_name} /></a> : <span className="admin-report-image-placeholder"><AppIcon name="camera" /></span>
}

export function IssueReportsAdminView({ language = 'en', onSeenChange }) {
  const l = labels[language] ?? labels.en
  const [filters, setFilters] = useState({ search: '', status: '', category: '', date_from: '', date_to: '', page: 1 })
  const [payload, setPayload] = useState({ data: [], current_page: 1, last_page: 1 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState(null); const [draft, setDraft] = useState({ status: 'new', public_message: '' }); const [saving, setSaving] = useState(false)
  const queryKey = useMemo(() => JSON.stringify(filters), [filters])
  const load = useCallback(async (silent = false) => { if (!silent) setLoading(true); try { const data = await getAdminIssueReports(JSON.parse(queryKey)); setPayload(data); setError('') } catch (e) { setError(e.message) } finally { if (!silent) setLoading(false) } }, [queryKey])
  useEffect(() => { const timer = window.setTimeout(() => load(), filters.search ? 350 : 0); return () => window.clearTimeout(timer) }, [filters.search, load])
  useEffect(() => { const timer = window.setInterval(() => { if (!selected && !document.activeElement?.matches?.('input,textarea,select')) load(true) }, 15000); return () => window.clearInterval(timer) }, [load, selected])
  async function open(report) { setLoading(true); try { const [detail] = await Promise.all([getAdminIssueReport(report.id), markAdminIssueReportSeen(report.id)]); setSelected(detail.data); setDraft({ status: detail.data.status, public_message: '' }); onSeenChange?.() } catch (e) { setError(e.message) } finally { setLoading(false) } }
  async function saveStatus() { if (!selected) return; setSaving(true); try { const result = await updateAdminIssueReportStatus(selected.id, draft); setSelected(result.data); setDraft({ status: result.data.status, public_message: '' }); await load(true); onSeenChange?.() } catch (e) { setError(e.message) } finally { setSaving(false) } }
  function updateFilter(key, value) { setFilters((current) => ({ ...current, [key]: value, page: key === 'page' ? Number(value) : 1 })) }

  return <section className="admin-reports">
    <div className="admin-reports__filters"><label><AppIcon name="search" /><input value={filters.search} onChange={(e) => updateFilter('search', e.target.value)} placeholder={l.search} /></label><select value={filters.status} onChange={(e) => updateFilter('status', e.target.value)}><option value="">{l.allStatus}</option>{Object.keys(statuses).map((key) => <option key={key} value={key}>{text(statuses, key, language)}</option>)}</select><select value={filters.category} onChange={(e) => updateFilter('category', e.target.value)}><option value="">{l.allCategory}</option>{Object.keys(categories).map((key) => <option key={key} value={key}>{text(categories, key, language)}</option>)}</select><input aria-label="From date" type="date" value={filters.date_from} onChange={(e) => updateFilter('date_from', e.target.value)} /><input aria-label="To date" type="date" value={filters.date_to} onChange={(e) => updateFilter('date_to', e.target.value)} /></div>
    {error && <div className="admin-reports__error"><AppIcon name="warning" />{error}</div>}
    <div className="admin-reports__table-wrap"><table><thead><tr><th>#</th><th>{l.reference}</th><th>{l.reporter}</th><th>{l.category}</th><th>{l.subject}</th><th>{l.evidence}</th><th>{l.status}</th><th>{l.sent}</th><th /></tr></thead><tbody>{!loading && payload.data?.length === 0 ? <tr><td colSpan="9" className="admin-reports__empty">{l.empty}</td></tr> : payload.data?.map((report, index) => <tr className={!report.first_seen_at ? 'is-unseen' : ''} key={report.id}><td>{(payload.current_page - 1) * 15 + index + 1}</td><td><strong>{report.reference_code}</strong>{!report.first_seen_at && <i className="admin-report-new-dot" />}</td><td><strong>{report.reporter.username}</strong><small>{report.reporter.email}</small></td><td>{text(categories, report.category, language)}</td><td>{report.subject}</td><td><AppIcon name="camera" /> {report.attachments_count}</td><td><span className={`admin-report-status is-${report.status}`}>{text(statuses, report.status, language)}</span></td><td>{formatDate(report.created_at, language)}</td><td><button type="button" onClick={() => open(report)}><AppIcon name="eye" />{l.view}</button></td></tr>)}</tbody></table>{loading && <div className="admin-reports__loading"><span /></div>}</div>
    <footer className="admin-reports__pagination"><button disabled={payload.current_page <= 1} onClick={() => updateFilter('page', payload.current_page - 1)}>‹</button><label>Page <input min="1" max={payload.last_page} type="number" value={payload.current_page} onChange={(e) => updateFilter('page', e.target.value)} /> / {payload.last_page}</label><button disabled={payload.current_page >= payload.last_page} onClick={() => updateFilter('page', payload.current_page + 1)}>›</button></footer>
    {selected && <div className="admin-report-modal-backdrop"><article className="admin-report-modal" role="dialog" aria-modal="true"><header><div><span className={`admin-report-status is-${selected.status}`}>{text(statuses, selected.status, language)}</span><h2>{selected.subject}</h2><p>{selected.reference_code} · {formatDate(selected.created_at, language)}</p></div><button onClick={() => setSelected(null)} type="button"><AppIcon name="close" /></button></header><div className="admin-report-modal__content"><main><section><h3>{l.details}</h3><p className="admin-report-description">{selected.description}</p><dl><div><dt>{l.reporter}</dt><dd>{selected.reporter.username}<small>{selected.reporter.email}</small></dd></div><div><dt>{l.category}</dt><dd>{text(categories, selected.category, language)}</dd></div></dl></section>{selected.attachments?.length > 0 && <section><h3>{l.evidence} ({selected.attachments.length})</h3><div className="admin-report-gallery">{selected.attachments.map((item) => <EvidenceImage reportId={selected.id} attachment={item} key={item.id} />)}</div></section>}</main><aside><section><h3>{l.history}</h3><ol><li><i /><div><strong>{text(statuses, 'new', language)}</strong><time>{formatDate(selected.created_at, language)}</time></div></li>{selected.updates?.map((update) => <li key={update.id}><i /><div><strong>{text(statuses, update.to_status, language)}</strong>{update.public_message && <p>{update.public_message}</p>}<small>{update.admin?.username}</small><time>{formatDate(update.created_at, language)}</time></div></li>)}</ol></section><section className="admin-report-update"><label>{l.status}<select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value })}>{Object.keys(statuses).map((key) => <option key={key} value={key}>{text(statuses, key, language)}</option>)}</select></label><label>{l.publicMessage}<textarea rows="5" maxLength="2000" value={draft.public_message} onChange={(e) => setDraft({ ...draft, public_message: e.target.value })} /></label><button disabled={saving || (draft.status === selected.status && !draft.public_message.trim())} onClick={saveStatus} type="button"><AppIcon name="save" />{saving ? '…' : l.save}</button></section></aside></div></article></div>}
  </section>
}
