import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faAnglesLeft,
  faAnglesRight,
  faArrowDownWideShort,
  faArrowRotateLeft,
  faBacteria,
  faBagShopping,
  faBell,
  faBolt,
  faBookmark,
  faBug,
  faCamera,
  faCartShopping,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faClockRotateLeft,
  faClock,
  faCloud,
  faCloudBolt,
  faCloudRain,
  faCloudShowersHeavy,
  faCloudSun,
  faCode,
  faComment,
  faComputerMouse,
  faCircleQuestion,
  faCrown,
  faDroplet,
  faEllipsis,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFloppyDisk,
  faFileArrowUp,
  faFolderOpen,
  faBoxArchive,
  faGamepad,
  faGaugeHigh,
  faGear,
  faHammer,
  faHeadphones,
  faHeart,
  faHouse,
  faKey,
  faLanguage,
  faLayerGroup,
  faLeaf,
  faLock,
  faLocationDot,
  faMagnifyingGlass,
  faMoon,
  faPaperPlane,
  faPenToSquare,
  faPlus,
  faRepeat,
  faReply,
  faRightFromBracket,
  faRightLeft,
  faRobot,
  faScrewdriverWrench,
  faSeedling,
  faShareNodes,
  faShieldHalved,
  faSmog,
  faSnowflake,
  faSprayCanSparkles,
  faSun,
  faTemperatureHalf,
  faThumbsUp,
  faTowerBroadcast,
  faTrashCan,
  faTriangleExclamation,
  faTrophy,
  faUser,
  faUserGroup,
  faUpDownLeftRight,
  faWheatAwn,
  faWind,
  faWorm,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

const iconMap = {
  repeat: faRepeat,
  reply: faReply,
  notifications: faBell,
  more: faEllipsis,
  home: faHouse,
  chat: faComment,
  bookmark: faBookmark,
  add: faPlus,
  air: faWind,
  aphid: faBug,
  arrowBack: faChevronLeft,
  arrowForward: faChevronRight,
  bolt: faBolt,
  bug: faBug,
  camera: faCamera,
  check: faCheck,
  controller: faGamepad,
  crown: faCrown,
  delete: faTrashCan,
  trash: faTrashCan,
  drop: faDroplet,
  eco: faLeaf,
  fern: faSeedling,
  fungus: faBacteria,
  fertilizer: faWheatAwn,
  shade: faShieldHalved,
  frost: faTemperatureHalf,
  speed: faGaugeHigh,
  groups: faUserGroup,
  hardware: faScrewdriverWrench,
  headset: faHeadphones,
  heart: faHeart,
  history: faClockRotateLeft,
  clock: faClock,
  help: faCircleQuestion,
  close: faXmark,
  leaf: faLeaf,
  logout: faRightFromBracket,
  mouse: faComputerMouse,
  pest: faBug,
  person: faUser,
  plant: faSeedling,
  plus: faPlus,
  profile: faUser,
  robot: faRobot,
  restartAlt: faArrowRotateLeft,
  save: faFloppyDisk,
  harvest: faBoxArchive,
  uproot: faSeedling,
  uploadFile: faFileArrowUp,
  folderOpen: faFolderOpen,
  search: faMagnifyingGlass,
  send: faPaperPlane,
  settings: faGear,
  shield: faShieldHalved,
  shop: faBagShopping,
  shoppingCart: faCartShopping,
  snail: faWorm,
  soil: faLayerGroup,
  sort: faArrowDownWideShort,
  sprout: faSeedling,
  switch: faRightLeft,
  temp: faTemperatureHalf,
  thumbUp: faThumbsUp,
  tool: faHammer,
  trophy: faTrophy,
  vine: faWheatAwn,
  eye: faEye,
  eyeOff: faEyeSlash,
  share: faShareNodes,
  live: faTowerBroadcast,
  wind: faWind,
  key: faKey,
  lock: faLock,
  location: faLocationDot,
  mail: faEnvelope,
  lightMode: faSun,
  darkMode: faMoon,
  weatherCloud: faCloud,
  weatherCloudSun: faCloudSun,
  weatherRain: faCloudRain,
  weatherHeavyRain: faCloudShowersHeavy,
  weatherStorm: faCloudBolt,
  weatherSnow: faSnowflake,
  weatherFog: faSmog,
  panelClose: faAnglesLeft,
  panelOpen: faAnglesRight,
  translate: faLanguage,
  edit: faPenToSquare,
  code: faCode,
  arrowDown: faChevronDown,
  arrowUp: faChevronUp,
  axe: faHammer,
  gun: faSprayCanSparkles,
  warning: faTriangleExclamation,
  move: faUpDownLeftRight,
}

export function AppIcon({ name, className = '', label, ...props }) {
  return (
    <FontAwesomeIcon
      aria-hidden={label ? undefined : true}
      aria-label={label}
      className={className}
      icon={iconMap[name] ?? iconMap.leaf}
      role={label ? 'img' : undefined}
      {...props}
    />
  )
}
