/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plant.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/plant.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  React.useEffect(() => {
    if (!actions) return
    Object.values(actions).forEach((a) => a && a.play && a.play())
    return () => Object.values(actions).forEach((a) => a && a.stop && a.stop())
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[0, -0.026, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="1st_Leaf_337">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="1st_Leaf001_336" />
                  <group name="1st_Stem_335" />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['1st_Leaf_Mat']} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['1st_Leaf_Mat']} skeleton={nodes.Object_13.skeleton} />
                </group>
              </group>
              <group name="2nd_Leaf_673">
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="2nd_Leaf001_672" />
                  <group name="2nd_Stem_671" />
                  <skinnedMesh name="Object_351" geometry={nodes.Object_351.geometry} material={materials['2nd_Leaf_Mat']} skeleton={nodes.Object_351.skeleton} />
                  <skinnedMesh name="Object_353" geometry={nodes.Object_353.geometry} material={materials['2nd_Leaf_Mat']} skeleton={nodes.Object_353.skeleton} />
                </group>
              </group>
              <group name="3rd_Leaf_1009">
                <group name="GLTF_created_2">
                  <primitive object={nodes.GLTF_created_2_rootJoint} />
                  <group name="3rd_Leaf001_1008" />
                  <group name="3rd_Stem_1007" />
                  <skinnedMesh name="Object_691" geometry={nodes.Object_691.geometry} material={materials['3rd_Leaf_Mat']} skeleton={nodes.Object_691.skeleton} />
                  <skinnedMesh name="Object_693" geometry={nodes.Object_693.geometry} material={materials['3rd_Leaf_Mat']} skeleton={nodes.Object_693.skeleton} />
                </group>
              </group>
              <group name="4th_Leaf_1345">
                <group name="GLTF_created_3">
                  <primitive object={nodes.GLTF_created_3_rootJoint} />
                  <group name="4th_Leaf001_1344" />
                  <group name="4th_Stem_1343" />
                  <skinnedMesh name="Object_1031" geometry={nodes.Object_1031.geometry} material={materials['4th_Leaf_Mat']} skeleton={nodes.Object_1031.skeleton} />
                  <skinnedMesh name="Object_1033" geometry={nodes.Object_1033.geometry} material={materials['4th_Leaf_Mat']} skeleton={nodes.Object_1033.skeleton} />
                </group>
              </group>
              <group name="5th_Leaf_1681">
                <group name="GLTF_created_4">
                  <primitive object={nodes.GLTF_created_4_rootJoint} />
                  <group name="5th_Leaf001_1680" />
                  <group name="5th_Stem_1679" />
                  <skinnedMesh name="Object_1371" geometry={nodes.Object_1371.geometry} material={materials['5th_Leaf_Mat']} skeleton={nodes.Object_1371.skeleton} />
                  <skinnedMesh name="Object_1373" geometry={nodes.Object_1373.geometry} material={materials['5th_Leaf_Mat']} skeleton={nodes.Object_1373.skeleton} />
                </group>
              </group>
              <group name="Pot_0" rotation={[Math.PI / 2, 0, 0]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Pot_Mat} />
              </group>
              <group name="Soil_1" scale={[0.862, 0.107, 0.862]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Soil_Mat} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/plant.gltf')
